const express = require("express");
const categoryRoutes = require("./categories");
const userRoutes = require("./users");
const productRoutes = require("./products");
const settingsRoutes = require("./master-data");
const homeRoutes = require("./home");
const reviewsRoutes = require("./reviews");
const galleryRoutes = require("./gallery");
const promotionRoutes = require("./promotions");
const router = express.Router();
const adminAuth = require("../../middleware/admin-auth");
const categoryCtrl = require("../../controllers/admin/categories");
const tnxRoutes = require("./transaction");
const subscriptionCtrl = require("../../controllers/admin/subscription");
const dashboardRoutes = require("./dashboard");
const shiprocketRoutes = require("./shiprocket");
const ordersRoutes = require("./orders");
const supportCtrl = require("../../controllers/admin/support");
const enquiryCtrl = require("../../controllers/admin/enquiry");

router.use("/categories", adminAuth, categoryRoutes);
router.use("/users", adminAuth, userRoutes);
router.use("/products", adminAuth, productRoutes);
router.use("/master-data", adminAuth, settingsRoutes);
router.use("/home", adminAuth, homeRoutes);
router.use("/reviews", adminAuth, reviewsRoutes);
router.use("/gallery", adminAuth, galleryRoutes);
router.use("/promotions", adminAuth, promotionRoutes);
router.use("/transactions", adminAuth, tnxRoutes);
router.use("/subscriptions", adminAuth, subscriptionCtrl.getSubscription);
router.use("/dashboard", adminAuth, dashboardRoutes);
router.use("/delivery", shiprocketRoutes);
router.get("/categoryTree", adminAuth, categoryCtrl.getCategoryTree);
router.use("/orders", adminAuth, ordersRoutes);
router.get("/support", adminAuth, supportCtrl.getSupport);
router.put("/support/:supportId", adminAuth, supportCtrl.updateSupport);
router.get("/contact-us", adminAuth, enquiryCtrl.getEnquiry);

module.exports = router;
